import { Position, Range } from 'vscode-languageserver/node';
import { RawSourceMap } from 'source-map';
import {
    parseSourceMap,
    mapJsxPositionToPugPosition,
    mapJsxRangeToPugRange,
    mapPugPositionToJsxPosition,
    destroySourceMapData,
    JsxPugSourceMapData
} from '../jsxPugMapping';

const p = (l: number, c: number): Position => Position.create(l, c);
const r = (sl: number, sc: number, el: number, ec: number): Range => Range.create(sl, sc, el, ec);

describe('jsxPugMapping', () => {
  // Conceptual simple source map:
  // Pug: "p Hello" (length 7)
  // JSX: "<p>Hello</p>" (length 12)
  // Mapping:
  //   JSX line 0, col 1 ('p' in <p>) -> Pug line 0, col 0 ('p')
  //   JSX line 0, col 4 ('H' in Hello) -> Pug line 0, col 2 ('H')
  //   JSX line 0, col 8 ('o' in Hello) -> Pug line 0, col 6 ('o')
  //   JSX line 0, col 11 ('p' in </p>) -> Pug line 0, col 0 ('p') (might map to tag start/end)

  const mockRawSourceMap: RawSourceMap = {
    version: 3,
    sources: ['test.pug'], // Assume the source is named 'test.pug'
    names: ['p', 'Hello'], // Names used if any (not typical for this simple map)
    // Mappings: "AAAA,EAAIA,CAAK,CACVC" (example, would need actual generation)
    // A: JSX col 0 -> source 0, line 0, col 0, name 0 (for <p>)
    // A: JSX col 1 -> source 0, line 0, col 0 (for p in <p>)
    // C: JSX col 2 -> no change
    // A: JSX col 3 -> no change
    // E: JSX col 4 -> source 0, line 0, col 2 (for H in Hello)
    // A: JSX col 5 -> source 0, line 0, col 3 (for e)
    // A: JSX col 6 -> source 0, line 0, col 4 (for l)
    // A: JSX col 7 -> source 0, line 0, col 5 (for l)
    // A: JSX col 8 -> source 0, line 0, col 6 (for o)
    // I: JSX col 9 -> no change (for < of </p>)
    // A: JSX col 10 -> no change (for / of </p>)
    // A: JSX col 11 -> source 0, line 0, col 0 (for p of </p>, mapping to start of original 'p' tag)
    // K: JSX col 12 -> no change (for > of </p>)
    // This is just a conceptual representation. VLQ encoding is complex.
    // For a real test, we need an actual source map string from Babel.
    // Let's use a very simple valid VLQ mapping for "p" -> "<p>"
    // Pug: "p" (L0 C0-1)
    // JSX: "<p>" (L0 C0-3)
    // Map: JSX L0 C1 ('p') to Pug L0 C0 ('p')
    mappings: "AACA", // JSX Line 1, Col 1 maps to Source 1 (index 0), Original Line 1, Original Col 0, Original Name (none)
    sourcesContent: ["p Hello"], // Original Pug content
  };

  const originalPugSimple = "p";
  const generatedJsxSimple = "<p>";
  const mockRawSourceMapSimple: RawSourceMap = {
      version: 3,
      sources: ["source.pug"],
      names: [],
      mappings: "AACA;", // Gen L1 C1 from Src1 L1 C0
      sourcesContent: [originalPugSimple]
  };


  const originalPugComplex = "p Hello ${name}";
  const generatedJsxComplex = "<p>Hello {name}</p>";
  // This source map is entirely fictional and needs to be generated by Babel for real testing
  const mockRawSourceMapComplex: RawSourceMap = {
    version: 3,
    sources: ['complex.pug'],
    names: ['name'], // For the {name} part
    mappings: 'AAAA,KAAIA,CAAM', // Highly simplified: <p> maps to p, {name} maps to ${name}
    sourcesContent: [originalPugComplex],
  };

  let mapDataSimple: JsxPugSourceMapData | null;
  let mapDataComplex: JsxPugSourceMapData | null;

  beforeAll(async () => {
    mapDataSimple = await parseSourceMap(mockRawSourceMapSimple, originalPugSimple, generatedJsxSimple);
    mapDataComplex = await parseSourceMap(mockRawSourceMapComplex, originalPugComplex, generatedJsxComplex);
  });

  afterAll(() => {
    if (mapDataSimple) destroySourceMapData(mapDataSimple);
    if (mapDataComplex) destroySourceMapData(mapDataComplex);
  });

  describe('parseSourceMap', () => {
    it('should parse a valid raw source map', async () => {
      expect(mapDataSimple).not.toBeNull();
      expect(mapDataSimple?.consumer).toBeDefined();
    });

    it('should return null for invalid source map json', async () => {
      const invalidJsonMap = "{ version: 3, /// invalid json";
      const data = await parseSourceMap(invalidJsonMap, "pug", "jsx");
      expect(data).toBeNull();
    });
  });

  describe('mapJsxPositionToPugPosition', () => {
    it('should map JSX position to Pug position for simple case', () => {
      if (!mapDataSimple) throw new Error("mapDataSimple not initialized");
      // JSX "<p>" : char 'p' is at L0, C1. Mapped from Pug "p" L0, C0
      expect(mapJsxPositionToPugPosition(p(0, 1), mapDataSimple)).toEqual(p(0, 0));
    });

    it('should return null if no mapping found or outside mapped JSX', () => {
      if (!mapDataSimple) throw new Error("mapDataSimple not initialized");
      expect(mapJsxPositionToPugPosition(p(0, 0), mapDataSimple)).toBeNull(); // Before 'p' in <p>
      expect(mapJsxPositionToPugPosition(p(0, 2), mapDataSimple)).toBeNull(); // After 'p' in <p> (assuming exact map)
    });

    // TODO: Add more tests with more complex, realistic source maps from Babel
  });

  describe('mapPugPositionToJsxPosition', () => {
    it('should map Pug position to JSX position for simple case', () => {
      if (!mapDataSimple) throw new Error("mapDataSimple not initialized");
      // Pug "p": char 'p' is at L0, C0. Mapped to JSX "<p>" L0, C1
      expect(mapPugPositionToJsxPosition(p(0, 0), mapDataSimple)).toEqual(p(0, 1));
    });

    it('should return null if no mapping found for Pug position', () => {
        if (!mapDataSimple) throw new Error("mapDataSimple not initialized");
        // Example: position beyond actual pug content (if map is strict)
        expect(mapPugPositionToJsxPosition(p(0, 5), mapDataSimple)).toBeNull();
    });

    // TODO: Add more tests with more complex, realistic source maps
  });

  describe('mapJsxRangeToPugRange', () => {
    it('should map a JSX range to a Pug range', () => {
        if (!mapDataSimple) throw new Error("mapDataSimple not initialized");
        // JSX Range for 'p' in "<p>" is r(0,1,0,2)
        // Expected Pug range for 'p' is r(0,0,0,1)
        const jsxRange = r(0,1,0,2);
        const expectedPugRange = r(0,0,0,1); // Assuming 'p' in pug is L0 C0 to L0 C1

        // This depends heavily on the mockRawSourceMapSimple's mappings.
        // AACA means: Gen L1 C1 from Src1 L1 C0.
        // So, JSX p(0,1) -> Pug p(0,0)
        // If jsxRange.end is p(0,2) (exclusive end), originalPositionFor for line:1, col:2 (1-based)
        // might map to pug p(0,1) (exclusive end of 'p') or be null.
        // Let's adjust the test to what originalPositionFor would likely return.
        // If originalPositionFor(1,2) is null, then pugEndPosition would be null.
        // If originalPositionFor(1,1) maps to line:1, col:0 (0-based)
        // and originalPositionFor(1,2) maps to line:1, col:1 (0-based) (if it maps char by char)
        // Then we expect r(0,0,0,1)
        const mappedRange = mapJsxRangeToPugRange(jsxRange, mapDataSimple);
        expect(mappedRange).toEqual(expectedPugRange);
    });

    // TODO: Add tests for ranges spanning multiple mappings, or unmappable parts
  });

});
